project_id = "oypfjcbmxzdcjbidsnqx"

[functions.ai-tutor-rag]
verify_jwt = false

[functions.admin-list-users]
verify_jwt = false

[functions.admin-delete-user]
verify_jwt = false

[functions.admin-create-user]
verify_jwt = false

[functions.admin-stats]
verify_jwt = false

[functions.admin-analytics]
verify_jwt = false

[functions.quiz-attempt]
verify_jwt = false

[functions.admin-export-data]
verify_jwt = false
